services:
  - type: web
    name: guvi-honeypot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0: --timeout 60
    envVars:
      - key: API_KEY
        value: guvi_secret_123
      - key: CALLBACK_URL
        value: https://hackathon.guvi.in/api/updateHoneyPotFinalResult
      - key: MIN_MESSAGES_FOR_CALLBACK
        value: "4"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "10000"
